### ISSUE TITLE
Unexpected response causing IndexError?

### ISSUE THREAD

**Issue by 7235201** [talwrii/llmcli#1]
response = response.text.splitlines()[-4]
IndexError: list index out of range
    raise Exception("Incorrect response from OpenAI API") from exc
Exception: Incorrect response from OpenAI API

**Comment by talwrii** [comment]
Hmm you might be logged out:

Try

```
llmci chatgpt --login
```

And see if works after that.

Otherwise you can un with

```
python3 -m pdb $(which llmcli) "prompt"
```

And examine response.text to see what's wrong with it. Depending on the problem this might need some changes upstream in the library this uses.

**Comment by talwrii** [comment]
I'm going to close this cause open loops and all that. But if you find the problematic response we can reopen and fix this.
